version: "2"
services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=
    volumes:
      - ./config:/config
      - ./movies:/data
    restart: unless-stopped
